rules: []
rulesConfigs: []
hooks: []
pages: []
resourceServers:
  - name: Budget Assistant
    identifier: https://develop.budget.lednova.io
    allow_offline_access: false
    scopes:
      - value: read:client_grants
        description: Read Client Grants
      - value: create:client_grants
        description: Create Client Grants
      - value: delete:client_grants
        description: Delete Client Grants
      - value: update:client_grants
        description: Update Client Grants

      - value: transaction:create
        description: Create Transactions
      - value: transaction:read
        description: Read Transactions
      - value: transaction:delete
        description: Delete Transactions
      - value: transaction:edit
        description: Edit Transactions

      - value: role:create
        description: Create Identity Role
      - value: role:edit
        description: Edit Identity Role
      - value: role:read
        description: Read Identity Role
      - value: role:delete
        description: Delete Identity Role
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: Auth0 Management API (Test Application)
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_basic
  - name: Budget Assistant (Test Application)
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_basic
  - name: Default App
    allowed_clients: []
    allowed_origins:
      - http://localhost:65214
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_basic
    web_origins:
      - http://localhost:65214
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - Auth0 Management API (Test Application)
      - Budget Assistant (Test Application)
      - Default App
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      strategy_version: 2
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Auth0 Management API (Test Application)
      - Budget Assistant (Test Application)
      - Default App
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  sandbox_version: "16"
emailProvider: {}
emailTemplates: []
clientGrants:
  - client_id: Budget Assistant (Test Application)
    audience: https://develop.budget.lednova.io
    scope:
      - read:client_grants
      - create:client_grants
      - delete:client_grants
      - update:client_grants
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles:
  - name: SuperAdmin
    description: Application super admins
    permissions: []
branding:
  templates: []
prompts:
  customText: {}
  universal_login_experience: new
migrations: {}
actions: []
triggers: {}
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
themes: []
