
node {
    Map<String, String> buildParameters = new HashMap<String, String>()
    buildParameters.put('imageRepository', 'lednev/budget-assistant.api')

    def dockerImage

    sh('export GIT_SSL_NO_VERIFY=1')
    stage('Clone repository') {       
        checkout scm
    }
    
    stage('Check environment') {
        gitCommit = sh(script: 'git describe --always', returnStdout: true)
        buildParameters.put('gitCommit', gitCommit.trim())

        switch (env.BRANCH_NAME) {
            case 'develop':
                buildParameters.put('taskDefinition', 'development')
                break

            case 'main':
                buildParameters.put('taskDefinition', 'production')
                break
        }
        // -${buildParameters.get('gitCommit')
        String imageFullName = "${buildParameters.get('imageRepository')}:${buildParameters.get('taskDefinition')}"
        buildParameters.put('imageFullName', imageFullName)

        sendNotification("<b>BudgetAssistant.API</b> - ${buildParameters.get('taskDefinition')}%0Abuild started")
         
    }

    stage('Build and Push service image') {
        dockerImage = docker.build(buildParameters.get('imageFullName'), ' -f ./BudgetAssistantBackend/BudgetAssistant.API/Dockerfile ./BudgetAssistantBackend/')
        docker.withRegistry('', 'DockerHub') {
            dockerImage.push()
        }
    }

    stage('Update server app'){
        sh("docker-compose -p BudgetAssistant -f docker-compose.${buildParameters.get('taskDefinition')}.yml pull")
        sh("docker-compose -p BudgetAssistant -f docker-compose.${buildParameters.get('taskDefinition')}.yml up --detach")
        sh("docker image prune -f")

        sendNotification("<b>BudgetAssistant.API</b> - ${buildParameters.get('taskDefinition')}%0AUp and running!")
    }

    def sendNotification(message){
        sh("curl https://api.telegram.org/bot2118332947:AAHSpNoS7TuUmE83eEAQ8kqJp110wxu9rsg/sendMessage?chat_id=-1001707520031&parse_mode=HTML&text=$message")
    }
}

